// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtlfvkBvIK7guXbC6aR_rqg4YC_wkjjCQ',
    appId: '1:738280069981:web:20d9205fd4d48dfc8926b4',
    messagingSenderId: '738280069981',
    projectId: 'plant-app-3b4e7',
    authDomain: 'plant-app-3b4e7.firebaseapp.com',
    storageBucket: 'plant-app-3b4e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKoV8QETJhvFHFHFTL7xEp-c2t4dGJURE',
    appId: '1:738280069981:android:2dbcb069bba38c808926b4',
    messagingSenderId: '738280069981',
    projectId: 'plant-app-3b4e7',
    storageBucket: 'plant-app-3b4e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg_3gu9sdsFkXSpFaijuDUvh1pSPIcwck',
    appId: '1:738280069981:ios:e8942d93786e8a798926b4',
    messagingSenderId: '738280069981',
    projectId: 'plant-app-3b4e7',
    storageBucket: 'plant-app-3b4e7.firebasestorage.app',
    iosBundleId: 'com.example.plantCareApp',
  );
}
